### PR TITLE
next: Svelte 5

### PR DESCRIPTION
**Pull request by huntabyte**
Getting this PR rolling so that when the time comes this project is ready to go with Svelte 5! There are still a few things that need addressed but the core functionality is there, all running Svelte 5. 🚀

One pain point atm is being able to differentiate between regular callback functions and Svelte components, now that [components are now functions themselves](https://svelte-5-preview.vercel.app/docs/breaking-changes#components-are-no-longer-classes).

### Due outs
- [ ] - Determine how to handle situations where the argument to a function could be one of `Component | string | ((data: ToastData) => string | Component)` (related: https://github.com/sveltejs/svelte/issues/9774#issuecomment-2172713821)
- [ ] - Properly infer the expected `componentProps` type when passing a custom component to the various `toast.X` methods
- [ ] - Document that instead of dispatching a `closeToast` event, the custom toast components should accept an optional `closeToast` prop which we pass when rendering out the toast in the `<Toaster />`
- [ ] - Document the various `snippet` props that replace the custom `slot`s

### CODE REVIEW

**Comment by wobsoriano** [comment]
The real mvp. Thanks so much

**Comment by huntabyte** [comment]
Hey @wobsoriano, regarding the issue of determining if a function is a component or not, the Svelte team seems hesitant to introduce such a predicate, meaning we'd have to modify the APIs a bit and basically not allow components to be passed in places that also take other callbacks.

**Comment by huntabyte** [comment]
Alrighty, @wobsoriano. After speaking to the Svelte team, it doesn't seem like they are going to provide a way to discriminate between "Component functions" and "Regular functions," so we'll have to adjust how we handle (I believe only the `toast.promise`).

I'll work on some API options for it unless you have some ideas already!

**Comment by wobsoriano** [comment]
Man @huntabyte, thanks so much! I appreciate you talking to the Svelte team for this one :D

**Comment by shyakadavis** [comment]
Hi;

> a way to discriminate between "Component functions" and "Regular functions,"

Might be of some interest: https://github.com/sveltejs/svelte/issues/9774#issuecomment-2266343301

**Comment by huntabyte** [comment]
> Hi;
> 
> > a way to discriminate between "Component functions" and "Regular functions,"
> 
> Might be of some interest: [sveltejs/svelte#9774 (comment)](https://github.com/sveltejs/svelte/issues/9774#issuecomment-2266343301)

Hey @shyakadavis, while this might be a nice "workaround," I don't particularly like the idea of relying on something that isn't advertised as always being true. That hack seems to rely on something that Svelte could potentially change in the future in a `patch` release (since it isn't advertised as an API/acceptable way to handle this scenario).

I'm leaning toward a more explicit API here for long-term stability/predictability.

**Comment by huntabyte** [comment]
Closing in favor of #126 which we'll be able  to do `@next` releases from

**Pull request closed without merging**
